# use libft \
◦ write\
◦ ft_printf \
◦ signal \
◦ sigemptyset \
◦ sigaddset \
◦ sigaction \
◦ kill \
◦ getpid \
◦ malloc \
◦ free \
◦ pause \
◦ sleep \
◦ usleep \
◦ exit \
one global variable per program (client and server)

# PROGRAMS! It has to run so implement main's


